Repository postmanlabs/postman-sandbox, pull requests merged in 2018-12, with the labels that each got.

#362 chore(package): update karma to version 3.1.3
  package-lock.json
  package.json
Labels: greenkeeper

#367 Greenkeeper/eslint plugin jsdoc 3.12.0
  package-lock.json
  package.json
Labels: greenkeeper

#370 Greenkeeper/eslint plugin jsdoc 3.14.0
  package-lock.json
  package.json
Labels: greenkeeper

#373 Add AJV to Sandbox
  CHANGELOG.md
  lib/environment.js
  lib/sandbox/pmapi.js
  package-lock.json
  package.json
  test/system/bootcode-dependencies.test.js
  test/unit/sandbox-libraries/ajv.test.js
Labels: enhancement

#374 Use getter for pm.request.to and pm.response.to assertions
  lib/sandbox/pmapi.js
  test/unit/sandbox-libraries/pm.test.js
Labels: bug

#375 Add tests for JSON schema assertions
  package-lock.json
  test/unit/sandbox-libraries/chai-postman.test.js
Labels: tests
